dash-db:
  data:
    redis-password: "${redis.password}"

origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

global:
  data:
    REDIS_HOST: "${redis.host}" # If external
    REDIS_PORT: ${redis.port}   # If external
    REDIS_PASSWORD: "${redis.password}"

