nameOverride: ''

imagePullSecrets: []
image:
  pullPolicy: IfNotPresent
  repository: apps
  tag: 0.1.1

commonAnnotations: {}
commonLabels: {}

redis:
  enabled: false
  nameOverride: ''
  auth:
    password: apps

redisService:
  host: localhost
  port: 6379

service:
  type: ClusterIP
  annotations: {}
  protocol: https
  port: 443
  containerPort: 5000
  nodePort: null

serviceAccount:
  create: true
  name: zimagi-command

psp:
  create: true
containerSecurityContext:
  enabled: true
  privileged: false
podSecurityContext:
  enabled: true
  fsGroup: 1001

replicaCount: 1
updateStrategy:
  type: RollingUpdate

affinity: {}
podAffinityPreset: ''
podAntiAffinityPreset: soft
nodeAffinityPreset:
  key: ''
  type: ''
  values: []

priorityClassName: ''
nodeSelector: {}
tolerations: []

resources:
  limits: {}
  requests: {}

containerPort: 5000
livenessProbe:
  failureThreshold: 1
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 90
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

extraEnvVarsCM: []
extraEnvVarsSecret: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  averageUtilization: 70

ingress:
  enabled: false
  className: ''
  annotations: {}
  hostname: ''
  extraHosts: []
  path: /
  pathType: ImplementationSpecific
  extraPaths: []
  tls: false
  certManager: false
  selfSigned: false
  extraTls: {}
