apiVersion: v2
name: ghost
description: A Helm chart for Kubernetes
appVersion: 5.30.1
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  tags:
  - ghost-database
  version: 9.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
type: application
version: 0.1.7
appVersion: "1.16.0"
