apiVersion: v2
version: 2.0.3
appVersion: 5

name: ghost
type: application
description: A Helm chart for deploying a Ghost application.
home: https://github.com/econradar/charts

dependencies:
  - condition: mysql.enabled
    name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: zimagi-lib
    repository: https://charts.zimagi.com
    version: 0.x.x

maintainers:
- email: erik@econradar.com
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian@econradar.com
  name: adrianwebb
  url: https://github.com/adrianwebb
