registry:
  type: "kubernetes.io/dockerconfigjson"
  data:
    ".dockerconfigjson": '${registry_credential}'

ghost-db:
  data:
    mysql-root-password: "${mysql.password}"
    mysql-replication-password: "${mysql.password}"
    mysql-password: "${mysql.password}"

origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

global:
  data:
    # see https://ghost.org/docs/config/#configuration-options
    database__connection__password: "${mysql.password}"

    mail__options__auth__user: "${mailgun_user}"
    mail__options__auth__pass: "${mailgun_password}"
