ghost-db:
  data:
    mysql-root-password: "${mysql.password}"
    mysql-replication-password: "${mysql.password}"
    mysql-password: "${mysql.password}"

origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

global:
  data:
    # see https://ghost.org/docs/config/#configuration-options
    database__connection__host: "${mysql.host}"
    database__connection__port: "${mysql.port}"
    database__connection__user: "${mysql.user}"
    database__connection__password: "${mysql.password}"
    database__connection__database: "${mysql.database}"
    database__connection__ssl__ca: "${mysql.ca_cert}"

    mail__options__auth__user: "${mailgun_user}"
    mail__options__auth__pass: "${mailgun_password}"
