nameOverride: ghost

labels: {}
annotations: {}

mysql:
  enabled: true
  auth:
    existingSecret: ghost-db # keys: mysql-root-password, mysql-replication-password, mysql-password
    database: ghost
    username: ghost
  primary:
    persistence:
      enabled: true
      size: 10Gi

image:
  pullSecrets: []
  pullPolicy: IfNotPresent
  repository: registry.hub.docker.com
  image: null # Custom Docker image (required)
  tag: null   # Custom Docker image (required)

pvc:
  claims:
    images:
      accessMode: ReadWriteOnce
      size: 5Gi
    files:
      accessMode: ReadWriteOnce
      size: 5Gi
  mounts:
    "/var/lib/ghost/content/images": images
    "/var/lib/ghost/content/files": files

volumes:
  config: {}
  secret: {}

deployment:
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

  priorityClassName: ""
  affinity: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []

  nodeSelector: {}
  tolerations: []
  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits: {}

  env:
    database__connection__host: '{{ include "ghost.mysql.fullname" . }}'
    database__connection__port: 3306
    database__connection__database: "{{ .Values.mysql.auth.database }}"
    database__connection__user: "{{ .Values.mysql.auth.username }}"

  config:
    - global
  secrets:
    - global

  protocol: HTTP
  port: 2368

  livenessProbe:
    endpoint: "/ghost/api/admin/site/"
    failureThreshold: 1
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

  readinessProbe:
    endpoint: "/ghost/api/admin/site/"
    failureThreshold: 1
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  avgCpuUtilization: 50

service:
  type: ClusterIP
  protocol: http
  port: 80

ingress:
  className: ''
  hosts: []
  tls: []

services:
  portal:
    autoscaling:
      enabled: false

    service:
      enabled: true
    ingress:
      enabled: false
      # hosts:
      #   - host: "${domain}"
      #   - host: "www.${domain}"
      # tls:
      #   - secretName: origin-cert
