apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: apps
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ include "common.tplvalues.render" (dict "value" $value "context" $) | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      name: api
      protocol: TCP
      {{- if and (eq "NodePort" .Values.service.type) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: apps
